attributes:
  nuage_net_partition_name:
    value: 'FUEL'
    label: 'Nuage Net Partition name'
    description: 'Nuage Net Partition name for VSD'
    weight: 20
    type: "text"
  nuage_vsd_ip:
    value: '10.20.0.7:8443'
    label: 'VSD IP address'
    description: 'VSD Management IP address'
    weight: 30
    type: "text"
  nuage_vsd_username:
    value: 'csproot'
    label: 'VSD username'
    description: 'VSD user'
    weight: 40
    type: "text"
  nuage_vsd_password:
    value: 'csproot'
    label: 'VSD password'
    description: 'VSD password'
    weight: 50
    type: "text"
  nuage_vsd_organization:
    value: 'csp'
    label: 'VSD organization name'
    description: 'VSD organization'
    weight: 60
    type: "text"
  nuage_base_uri_version:
    value: 'v3_0'
    label: 'Nuage base uri version'
    description: 'Nuage base uri version number'
    weight: 70
    type: "text"
  nuage_active_vsc_ip:
    value: '10.20.0.200'
    label: 'Active VSC IP address'
    description: 'Active VSC IP address'
    weight: 80
    type: "text"
  nuage_backup_vsc_ip:
    value: ''
    label: 'Backup VSC IP address'
    description: 'Backup VSC IP address'
    weight: 90
    type: "text"
  metadata_proxy_shared_secret:
    value: 'NuageNetworksSharedSecret'
    label: 'Nuage metadata agent shared secret password'
    description: 'Nuage metadata proxy shared secret password'
    weight: 100
    type: "text"
  metadata_port:
    value: '9697'
    label: 'Nuage Metadata agent port number'
    description: 'Nuage Metadata agent port number'
    weight: 110
    type: "text"
  nova_metadata_ip:
    value: '172.21.11.31'
    label: 'Nova metadata server IP address'
    description: 'Nova metadata server IP address'
    weight: 120
    type: "text"
  nova_metadata_port:
    value: '8775'
    label: 'Nova metadata port number'
    description: 'Nova metadata port number'
    weight: 130
    type: "text"
  nova_client_version:
    value: '2'
    label: 'Nova client version'
    description: 'Nova client version'
    weight: 140
    type: "text"
  nova_os_username:
    value: 'nova'
    label: 'Nova OS Username'
    description: 'Nova OS Username'
    weight: 150
    type: "text"
  nova_os_password:
    value: 'service'
    label: 'Nova OS password'
    description: 'Nova OS password'
    weight: 160
    type: "text"
  nova_os_tenant_name:
    value: 'service'
    label: 'Nova OS tenant name'
    description: 'Nova OS tenant name'
    weight: 170
    type: "text"
  nova_os_auth_url:
    value: 'http://infra-keystone:5000/v2.0'
    label: 'Nova OS auth URL'
    description: 'Nova OS auth URL'
    weight: 180
    type: "text"
  metadata_agent_start_with_ovs:
    value: 'true'
    label: 'Nuage metadata agent enable flag'
    description: 'Nuage metadata agent enable flag'
    weight: 190
    type: "text"
  nova_api_endpoint_type:
    value: 'publicURL'
    label: 'Nova API endpoint type'
    description: 'Nova API endpoint type'
    weight: 200
    type: "text"
