attributes:
  # Show Nuage plugin option only in supported network config
  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        message: "Please use Neutron with VLAN segmentation, the only network type supported with Nuage plugin."
  nuage_net_partition_name:
    value: ''
    label: 'Nuage Net Partition name'
    description: 'Nuage Net Partition name for VSD'
    weight: 20
    type: "text"
  nuage_vsd_ip:
    value: ''
    label: 'VSD IP address'
    description: 'VSD Management IP address'
    weight: 30
    type: "text"
  nuage_vsd_username:
    value: ''
    label: 'VSD username'
    description: 'VSD user'
    weight: 40
    type: "text"
  nuage_vsd_password:
    value: ''
    label: 'VSD password'
    description: 'VSD password'
    weight: 50
    type: "text"
  nuage_vsd_organization:
    value: ''
    label: 'VSD organization name'
    description: 'VSD organization'
    weight: 60
    type: "text"
  nuage_base_uri_version:
    value: ''
    label: 'Nuage base uri version'
    description: 'Nuage base uri version number'
    weight: 70
    type: "text"
  nuage_active_vsc_ip:
    value: ''
    label: 'Active VSC IP address'
    description: 'Active VSC IP address'
    weight: 80
    type: "text"
  nuage_backup_vsc_ip:
    value: ''
    label: 'Backup VSC IP address'
    description: 'Backup VSC IP address'
    weight: 90
    type: "text"
  metadata_port:
    value: ''
    label: 'Nuage Metadata agent port number'
    description: 'Nuage Metadata agent port number'
    weight: 100
    type: "text"
  nova_metadata_ip:
    value: ''
    label: 'Nova metadata server IP address'
    description: 'Nova metadata server IP address'
    weight: 110
    type: "text"
  nova_metadata_port:
    value: ''
    label: 'Nova metadata port number'
    description: 'Nova metadata port number'
    weight: 120
    type: "text"
  nova_client_version:
    value: ''
    label: 'Nova client version'
    description: 'Nova client version'
    weight: 130
    type: "text"
  nova_os_username:
    value: ''
    label: 'Nova OS Username'
    description: 'Nova OS Username'
    weight: 140
    type: "text"
  nova_os_password:
    value: ''
    label: 'Nova OS password'
    description: 'Nova OS password'
    weight: 150
    type: "text"
  nova_os_tenant_name:
    value: ''
    label: 'Nova OS tenant name'
    description: 'Nova OS tenant name'
    weight: 160
    type: "text"
  nova_os_auth_url:
    value: ''
    label: 'Nova OS auth URL'
    description: 'Nova OS auth URL'
    weight: 170
    type: "text"
  metadata_agent_start_with_ovs:
    value: ''
    label: 'Nuage metadata agent enable flag'
    description: 'Nuage metadata agent enable flag'
    weight: 180
    type: "text"
  nova_api_endpoint_type:
    value: ''
    label: 'Nova API endpoint type'
    description: 'Nova API endpoint type'
    weight: 190
    type: "text"
