attributes:
  # Show Nuage plugin option only in supported network config
  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        message: "Please use Neutron with VLAN segmentation, the only network type supported with Nuage plugin."
  nuage_net_partition_name:
    value: ''
    label: 'Nuage Net Partition name'
    description: 'Nuage Net Partition name for VSD'
    weight: 20
    type: "text"
  nuage_vsd_ip:
    value: ''
    label: 'VSD IP address'
    description: 'VSD Management IP address'
    weight: 30
    type: "text"
  nuage_vsd_username:
    value: ''
    label: 'VSD username'
    description: 'VSD user'
    weight: 40
    type: "text"
  nuage_vsd_password:
    value: ''
    label: 'VSD password'
    description: 'VSD password'
    weight: 50
    type: "text"
  nuage_vsd_organization:
    value: ''
    label: 'VSD organization name'
    description: 'VSD organization'
    weight: 60
    type: "text"
  nuage_base_uri_version:
    value: ''
    label: 'Nuage base uri version'
    description: 'Nuage base uri version number'
    weight: 70
    type: "text"
  nuage_active_vsc_ip:
    value: ''
    label: 'Active VSC IP address'
    description: 'Active VSC IP address'
    weight: 80
    type: "text"
  nuage_backup_vsc_ip:
    value: ''
    label: 'Backup VSC IP address'
    description: 'Backup VSC IP address'
    weight: 90
    type: "text"
  metadata_port:
    value: '9697'
    label: 'Nuage Metadata agent port number'
    description: 'Nuage Metadata agent port number'
    weight: 100
    type: "text"
  nova_metadata_port:
    value: '8775'
    label: 'Nova metadata port number'
    description: 'Nova metadata port number'
    weight: 110
    type: "text"
  nova_region_name:
    value: 'RegionOne'
    label: 'Nova Region Name'
    description: 'Nova Region name'
    weight: 120
    type: "text"
  nova_api_endpoint_type:
    type: "radio"
    weight: 130
    value: "publicURL"
    label: "Nova API endpoint type"
    description: "Select Nova API endpoint type"
    values:
      - data: "publicURL"
        label: "publicURL"
      - data: "internalURL"
        label: "internalURL"
      - data: "adminURL"
        label: "adminURL"
  fuel_username:
    value: 'root'
    label: 'Fuel Node Login Username'
    description: 'Fuel Node Login Username'
    weight: 140
    type: "text"
  fuel_password:
    value: 'r00tme'
    label: 'Fuel Node Login Password'
    description: 'Fuel Node Login Password'
    weight: 150
    type: "text"
  nuage_enable_cms_script:
    value: ''
    label: 'Nuage CMS Enable Script'
    description: 'Nuage CMS Enable Script'
    weight: 160
    type: "text"
  nuage_plugin_version:
    value: '1.0'
    label: 'Nuage Fuel Plugin Version'
    description: 'Nuage Fuel Plugin Version'
    weight: 170
    type: "text"
  mos_cluster_name:
    value: ''
    label: 'Mirantis Openstack Cluster Name'
    description: 'Mirantis Openstack Cluster Name'
    weight: 180
    type: "text"
